config/routes.rb
Rails.application.routes.draw do

  resources :journals do
    resources :tasks do
      resources :descriptions
    end
  end

  devise_for :users, controllers: { 
    registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root to: 'home#index'

  # Categories Routes

  # get '/journals' => 'journals#index', as: 'journals'
  # get '/journals/new' => 'journals#new', as: 'new_journal'

  post '/journals' => 'journals#create'

  delete '/journals/:id' => 'journals#destroy', as: 'delete_journal'

  # get '/journals/:id' => 'journals#show', as: 'journal'

  # get '/journals/:id/edit' => 'journals#edit', as: 'edit_journal'

  # Tasks Routes

  # get '/journals/:journal_id/tasks' => 'tasks#index', as: 'journal_tasks'

  post '/journals/:journal_id/tasks' => 'tasks#create'

  delete '/journals/:journal_id/tasks/:id' => 'tasks#destroy', as: 'delete_journal_task'

  # get '/journals/:journal_id/tasks/new' => 'tasks#new', as: 'new_journal_task'

  # get '/journals/:journal_id/tasks/:id/edit' => 'tasks#edit', as: 'edit_journal_task'

  # get '/journals/:journal_id/tasks/:id' => 'tasks#show', as: 'journal_task'

  # Description Routes

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :journal
    has_many :descriptions, dependent: :destroy
    has_rich_text :description
    validate :not_past_due

    validates :name, presence: true, length: { maximum: 20 }
    validates :description, presence: true, length: { maximum: 2500 }
    validates :deadline, presence: true

    COMPLETED_OPTIONS = [%w[Started false], %w[Completed true]].freeze

    def not_past_due
        return if deadline.nil? || deadline.today?
    
        return errors.add(:deadline, 'is already past') if new_record? && deadline.past?
    
        unless new_record?
          old_deadline, new_deadline = deadline_change
    
          return if old_deadline.nil?
    
          return if (new_deadline == old_deadline) && !new_deadline.past?
    
          return errors.add(:deadline, 'is already past') if new_deadline.past?
        end
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_journal
    before_action :set_task, only: %i[show edit update destroy]

    def index
        redirect_to @journal
    end

    def show
        @description = @task.descriptions.build
    end

    def new
        @task = Task.new
    end

    def edit
    end

    def create
        @task = @journal.tasks.build(task_params)
        @task.position = @journal.get_next_task_position

        if @task.save
            redirect_to @journal
        else
            render :new
        end
    end

    def update
        if @task.update(task_params)
            redirect_to @journal
        else
            render :edit
        end
    end

    def destroy
        @task.destroy
        redirect_to @journal
    end

    private

    def set_journal
        @journal = current_user.journals.find(params[:journal_id])
    end

    def set_task
        @task = @journal.tasks.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:name, :description, :deadline, :completed)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [journal, task], class: 'mt-16 custom:mt-0') do |form| %>

    <% if task.errors.any? %>
        <ul class="error-message text-red-800 font-semibold">
            <% task.errors.each do |error| %>
                <li> <%= error.full_message %> </li>
            <% end %>
        </ul>
    <% end %>

    <label class="font-semibold text-4xl">Customize your task</label>
    <br/><br/>

    <%= form.text_field :name, placeholder: "✏️ Task Name", class: 'appearance-none rounded relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm', autocomplete: :off %>

    <br/>

    <%= form.rich_text_area :description, placeholder: "📃 Task Description", class: 'rounded', autocomplete: :off, maxlength: 2500 %>

    <br/>


    <%= form.label :deadline do%>
        <span>Set Deadline:</span>
    <% end %>
    <%= form.date_field :deadline %>

    <br/><br/>

    <%= form.label :completed do%>
      <span>Set Status:</span>
    <% end %>
    <%= form.select :completed, Task::COMPLETED_OPTIONS, class: "select" %>

    <br/><br/>

    <div class="category-buttons flex gap-8 font-semibold text-xl">
      <%= form.button class: "button start-now-two" do %> 
        <%= raw '<i class="fas fa-plus mr-3"></i>' if action_name.capitalize == 'Create' %>
        <%= raw '<i class="fas fa-plus mr-3"></i>' if action_name.capitalize == 'New' %>
        <%= raw '<i class="fas fa-edit mr-3"></i>' if action_name.capitalize == 'Update' %>
        <%= raw '<i class="fas fa-edit mr-3"></i>' if action_name.capitalize == 'Edit' %>
        <%= :new if action_name.capitalize == "New" %><%= :edit if action_name.capitalize == "Edit" %> <%= :task %>
      <% end %>

      <%= link_to journal, class: 'font-semibold text-red-800 text-xl' do%>
        Cancel
      <% end %>
    </div>

<% end %>

app/views/tasks/_navbar.html.erb
    <header class="header-home sticky top-0 z-10 flex justify-center items-center gap-10 py-8 custom:flex-col">

        <a href="/" class="header-span text-4xl font-extrabold text-gray-900">GoForIt</a>
        
        <nav>
            <ul class="nav_links flex gap-5 text-xl custom:text-md gap-2">
                <li class="font-semibold hover:text-gray-900"><%= link_to "Dashboard", journals_path %></li>
                <li class="font-semibold hover:text-gray-900"><%= link_to "Add Category", new_journal_path %></li>
                <li class="font-semibold hover:text-gray-900"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to sign-out?' } %></li>
            </ul>
        </nav>

    </header>

app/views/tasks/edit.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

<section id="new-task" class="new-task mt-16">

    <div class="flex gap-32 justify-center custom:flex-col-reverse">

        <%= render 'form', journal: @journal, task: @task %>

        <div>
            <%= image_tag("editing-body-task-animate.svg", :alt => 'edit category image', class: "edit__svg") %>
        </div>

    </div>

</section>

    <br/><br/>

    <footer class="mt-16 text-center">
        <span class="text-gray-700 text-xl font-semibold">by: CS155L_BM1</span>
    </footer>

    <br/><br/>

app/views/tasks/new.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

<section id="new-task" class="new-task mt-16">

    <div class="flex gap-32 justify-center custom:flex-col-reverse">

        <%= render 'form', journal: @journal, task: @task %>

        <div>
            <%= image_tag("add-tasks-animate.svg", :alt => 'add category image', class: "add__svg") %>
        </div>

    </div>

</section>

    <br/><br/>

    <footer class="mt-16 text-center">
        <span class="text-gray-700 text-xl font-semibold">by: CS155L_BM1</span>
    </footer>

    <br/><br/>

app/views/tasks/show.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

<section id="task-show" class="task-show">

        <div class="flex gap-32 justify-center custom:flex-col-reverse mt-16">
            <div>
                <div class="mt-16 text-xl">
                    <% label = task_label(@task) %>
                    <strong><%= @task.name %></strong>
                    <br/>
                    <i class='bx bxs-time' ></i>
                    <span>Deadline: <%= date_parse(@task.deadline) %></span>
                    <br/>
                    Status: <span class="has-text-<%= label[:status] %>">
                        <%= label[:message] %>
                    </span>

                    <br/><br/>

                    <div class="show-tasks-icons is-flex">
                        <%= link_to journal_path(@journal) do%>
                            <i class='bx bx-arrow-back is-size-5 font-semibold text-violet-800 text-3xl hover:text-violet-600' ></i>
                        <% end %>

                        <%= link_to edit_journal_task_path(@journal) do%>
                            <i class='bx bxs-cog is-size-5 font-semibold text-yellow-800 text-3xl hover:text-yellow-600' ></i>
                        <% end %>
                        <%= link_to journal_task_path(@journal), method: :delete, data: { confirm: 'Are you sure?' } do %>
                            <i class='bx bxs-trash is-size-5 font-semibold text-red-800 text-3xl hover:text-red-600' ></i>
                        <% end %>
                    </div>
                </div>

                <br/><br/>

                <div class="container show-task-details text-xl">
                    <strong>Task Description:</strong>
                    &nbsp;<%= @task.description %>
                </div>
            </div>

            <%= image_tag("mind-map-animate.svg", :alt => 'edit category image', class: "edit__svg") %>

        </div>


</section>