config/routes.rb
Rails.application.routes.draw do

  resources :journals do
    resources :tasks do
      resources :descriptions
    end
  end

  devise_for :users, controllers: { 
    registrations: "users/registrations",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end

  root to: 'home#index'

  # Categories Routes

  # get '/journals' => 'journals#index', as: 'journals'
  # get '/journals/new' => 'journals#new', as: 'new_journal'

  post '/journals' => 'journals#create'

  delete '/journals/:id' => 'journals#destroy', as: 'delete_journal'

  # get '/journals/:id' => 'journals#show', as: 'journal'

  # get '/journals/:id/edit' => 'journals#edit', as: 'edit_journal'

  # Tasks Routes

  # get '/journals/:journal_id/tasks' => 'tasks#index', as: 'journal_tasks'

  post '/journals/:journal_id/tasks' => 'tasks#create'

  delete '/journals/:journal_id/tasks/:id' => 'tasks#destroy', as: 'delete_journal_task'

  # get '/journals/:journal_id/tasks/new' => 'tasks#new', as: 'new_journal_task'

  # get '/journals/:journal_id/tasks/:id/edit' => 'tasks#edit', as: 'edit_journal_task'

  # get '/journals/:journal_id/tasks/:id' => 'tasks#show', as: 'journal_task'

  # Description Routes

end

app/models/journal.rb
class Journal < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

    validates :name,
        presence: true,
        length: { maximum: 20 }

    def get_next_task_position
        if tasks.none?(&:persisted?)
            1
        else
            tasks.order(position: :asc).last.position + 1.to_s
        end
    end
        
    def percent_complete
        return 0 if tasks.none?
        
        complete_tasks = tasks.select(&:completed?).count
        ((complete_tasks.to_f / tasks.count) * 100).round
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_journal, only: %i[show edit update destroy]

    def index
        @journals = current_user.journals
    end

    def show
    end

    def new
        @journal = current_user.journals.build
    end

    def edit
    end

    def create
        @journal = current_user.journals.build(journal_params)

        if @journal.save
            redirect_to journals_url, notice: 'Category has been successfully created'
        else
            render :new
        end

        # respond_to do |format|
        #     if @journal.save
        #         format.html do
        #         redirect_to journals_path,
        #                     success: 'Category has been created successfully'
        #     end
        #     format.json { render :show, status: :created, location: @journal }
        # else
        #     format.html { render :new, status: :unprocessable_entity }
        #     format.json do
        #         render json: @journal.errors, status: :unprocessable_entity
        #     end
        # end
    end

    def update
        respond_to do |format|
            if @journal.update(journal_params)
              format.html do
                redirect_to journals_path, success: 'Category has been updated successfully'
              end
              format.json { render :show, status: :ok, location: @journal }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json do
                render json: @journal.errors, status: :unprocessable_entity
              end
            end
        end
    end

    def destroy
        @journal.destroy
        respond_to do |format|
            format.html do
                redirect_to journals_url, success: "Category was successfully destroyed."
            end
            format.json { head :no_content }
        end
    end

    private

        def set_journal
            @journal = current_user.journals.find(params[:id])
        end

        def journal_params
            params.require(:journal).permit(:name)
        end
    end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_completed.html.erb
            <%#<div class="columns is-desktop is-multiline tasks-col"> %>
            <div class="tile tile-container is-ancestor">
            <%# if there is or are tasks available %>
                <% @journal.tasks.each do |task| %>
                    <% if task.completed? == false and task.deadline.today? %>
                    <%#<div class="column tasks-column"> %>
                    <div class="tile-contents">
                        <span class="task-status-label">
                            <%= raw task_label(task)[:html] %>
                        </span>
                        <br/>
                        <strong><%= task.name %></strong>  
                        <br/>
                        <span class="tasks-time">
                            <i class='bx bxs-time' ></i>         
                            <%= date_parse(task.deadline) %>
                        </span>
                        <br/>
                        <i class='bx bxs-chevron-right' ></i>
                        <span class='tasks-desc'>
                            <%= truncate(strip_tags(task.description.to_s), length: 100) %>
                        </span>
                        <div class='tasks-icons'>
                            <%# show task path %>
                            <%= link_to journal_task_path(@journal, task) do%>
                                <i class='bx bx-expand-alt' ></i>
                            <% end %>

                            <br/>

                            <%# edit task path %>
                            <%= link_to edit_journal_task_path(@journal, task) do%>
                                <i class='bx bxs-edit-alt'></i>
                            <% end %>

                            <br/>

                            <%# delete task %>
                            <%= link_to journal_task_path(@journal, task), method: :delete, data: {confirm: 'Are you sure?'} do%>
                                <i class='bx bxs-trash' ></i>
                            <% end %>
                        </div>
                    <% end %>
                    </div>
                <% end %>

                <br/>
            </div>

app/views/journals/_form.html.erb
<%= form_with(model: journal, class: 'mt-32 custom:mt-0') do |form| %>

    <% if journal.errors.any? %>
        <ul class="error-message text-red-800 font-semibold">
            <% journal.errors.each do |error| %>
                <li> <%= error.full_message %> </li>
            <% end %>
        </ul>
    <% end %>

    <label class="font-semibold text-4xl">Customize your work</label>
    <br/><br/>

    <%= form.text_field :name, placeholder: '✏️ Category Title', class: 'appearance-none rounded relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm', autocomplete: :off %>

    <br/>

    <div class="category-buttons flex gap-8 font-semibold text-xl">

        <%= form.button do%>
            <%= raw '<i class="fas fa-plus mr-3"></i>' if action_name.capitalize == 'Create' %>
            <%= raw '<i class="fas fa-plus mr-3"></i>' if action_name.capitalize == 'New' %>
            <%= raw '<i class="fas fa-edit mr-3"></i>' if action_name.capitalize == 'Update' %>
            <%= raw '<i class="fas fa-edit mr-3"></i>' if action_name.capitalize == 'Edit' %>
            <%= :new if action_name.capitalize == "New" %><%= :edit if action_name.capitalize == "Edit" %> Category
        <% end %>

        <%= link_to journals_path, class: 'font-semibold text-red-800 text-xl' do%>
            Cancel
        <% end %>

    </div>


<% end %>

app/views/journals/_nottoday.html.erb
<div class="container tiles">
    <div
        id="completed-top-card"
        class="box box2 your-tasks info-box box-bg mt-4 has-text-weight-semibold is-flex is-align-items-center is-justify-content-center"
    >
    <div class="is-size-3 has-text-centered">
    <svg id="taskLogo" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none">
        <path d="M19 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8l8-8V5a2 2 0 0 0-2-2zm-7 16v-7h7l-7 7z" stroke="white" stroke-width="1"></path>
    </svg>
        Your Tasks
    </div>
</div>

            
<div class="tile tile-container is-ancestor">
    <%# if there is or are tasks available %>
    <% @journal.tasks.each do |task| %>
        <% if task.completed? == false and !task.deadline.today? %>
        <div class="tile-contents">
            <span class="task-status-label">
                <%= raw task_label(task)[:html] %>
            </span>
            <br/>
            <strong><%= task.name %></strong>  
            <br/>
            <span class="tasks-time">
                <i class='bx bxs-time' ></i>         
                <%= date_parse(task.deadline) %>
            </span>
            <br/>
            <i class='bx bxs-chevron-right' ></i>
            <span class='tile-actions is-flex is-justify-content-flex-end'>
                <%= truncate(strip_tags(task.description.to_s), length: 100) %>
            </span>
            <div class='tasks-icons'>
                <%# show task path %>
                <%= link_to journal_task_path(@journal, task) do%>
                    <i class='bx bx-expand-alt' ></i>
                <% end %>

                <br/>

                <%# edit task path %>
                <%= link_to edit_journal_task_path(@journal, task) do%>
                    <i class='bx bxs-edit-alt'></i>
                <% end %>

                <br/>

                <%# delete task %>
                <%= link_to journal_task_path(@journal, task), method: :delete, data: {confirm: 'Are you sure?'} do%>
                    <i class='bx bxs-trash' ></i>
                <% end %>
            </div>
        <% end %>
        </div>
    <% end %>

    <br/>

    <% unless @journal.percent_complete == 0 %>
        <div class="container tiles">
            <div
                id="completed-top-card"
                class="box box2 completed info-box box-bg mt-4 has-text-weight-semibold is-flex is-align-items-center is-justify-content-center"
            >
                <div class="is-size-3 has-text-centered">
                <svg id="taskLogo" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none">
                    <path d="m2.394 13.742 4.743 3.62 7.616-8.704-1.506-1.316-6.384 7.296-3.257-2.486zm19.359-5.084-1.506-1.316-6.369 7.279-.753-.602-1.25 1.562 2.247 1.798z" stroke="white" stroke-width="1"></path>
                </svg>
                    Completed Tasks
                </div>
            </div>

            <div class="tile tile-container is-ancestor">
                <% @journal.tasks.each do |task| %>
                    <% unless task.completed? == false %>
                        <div class="tile-contents">
                            <%= raw task_label(task)[:html] %>
                            <br/>
                            <strong><%= task.name %></strong>  
                            <br/>
                            <span class="tasks-time">
                                <i class='bx bxs-time' ></i>         
                                <%= date_parse(task.deadline) %>
                            </span>
                            <br/>
                            <i class='bx bxs-chevron-right' ></i>
                            <span class='tasks-desc'>
                                <%= truncate(strip_tags(task.description.to_s), length: 100) %>
                            </span>
                            <br/>
                        <div class='tasks-icons'>
                            <%# show task path %>
                                <%= link_to journal_task_path(@journal, task) do%>
                                    <i class='bx bx-expand-alt' ></i>
                                <% end %>

                                <br/>

                                <%# edit task path %>
                                <%= link_to edit_journal_task_path(@journal, task) do%>
                                            <i class='bx bxs-edit-alt'></i>
                                <% end %>

                                <br/>

                            <%# delete task %>
                            <%= link_to journal_task_path(@journal, task), method: :delete, data: {confirm: 'Are you sure?'} do%>
                                        <i class='bx bxs-trash' ></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/journals/edit.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

<section id="edit-journal" class="edit-journal mt-16">

    <div class="flex gap-32 justify-center custom:flex-col-reverse">
    
        <%= render 'form', journal: @journal %>

        <div>
            <%= image_tag("editing-body-task-animate.svg", :alt => 'edit category image', class: "edit__svg") %>
        </div>

    </div>

</section>

    <footer class="mt-16 text-center">
        <span class="text-gray-700 text-xl font-semibold">by: CS155L_BM1</span>
    </footer>

    <br/><br/>

app/views/journals/index.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

<section id="index-journal" class="index-journal">

    <%# Show User Profile %>

        <div class="flex justify-center items-center gap-8 font-semibold text-2xl">
            <div>
                <i class='bx bxs-user-circle text-violet-900 mt-1' ></i>
                <%= current_user.username %>
            </div>

            <div>
                <i class='bx bxs-book-content text-violet-900 mt-1'></i>
                Your Categories
            </div>
        </div>

    <%# End %>

    <div class="journal-index grid grid-cols-4 gap-8 max-w-7xl mt-16 custom:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-4">
        <% @journals.each do |journal| %>
            <div class="journal__index bg-gray-50 border-2 border-gray-500 rounded-sm w-full p-8 custom:w-3/4 md:w-3/4 lg:w-3/4 xl:w-full 2xl:w-full">
                <% unless @journals.count == 0 %>
                    <div class="column journals-column">
                        <strong class="text-3xl whitespace-nowrap"><%= journal.name %></strong>
                        <br/>
                        <% if journal.tasks.count == 1 %>
                            <span>
                                <i class='bx bxs-notepad' ></i>
                                <%= journal.tasks.count %> Task
                            </span>
                        <% else %>
                            <span>
                                <i class='bx bxs-notepad' ></i>
                                <%= journal.tasks.count %> Tasks
                            </span>
                        <% end %>
                        <br/>
                        <span class='journal-time'>
                            <i class='bx bxs-time-five' ></i>
                            Started <%= time_ago_in_words(journal.created_at) %> ago
                        </span>
                        <br/>

                        <div class='journal-icons flex gap-2 mt-2'>
                            <%= link_to journal_path(journal) do%>
                                <i class='bx bxs-add-to-queue font-semibold text-violet-800 text-3xl hover:text-violet-600'></i>
                            <% end %>
                            <br/>
                            <%= link_to edit_journal_path(journal) do%>
                                <i class='bx bxs-edit font-semibold text-yellow-800 text-3xl hover:text-yellow-600'></i>
                            <% end %>
                            <br/>
                            <%= link_to journal, method: :delete, data: {confirm: 'Are you sure?'} do%>
                                <i class='bx bxs-trash font-semibold text-red-800 text-3xl hover:text-red-600'></i>
                            <% end %>
                        </div>
                <% end %>
            </div>
            </div>
        <% end %>
    </div>

</section>

app/views/journals/new.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

<section id="new-journal" class="new-journal mt-16">

    <div class="flex gap-32 justify-center custom:flex-col-reverse">

        <%= render 'form', journal: @journal %>

        <div>
            <%= image_tag("add-notes-animate.svg", :alt => 'add category image', class: "add__svg") %>
        </div>

    </div>

</section>

    <br/><br/>

    <footer class="mt-16 text-center">
        <span class="text-gray-700 text-xl font-semibold">by: CS155L_BM1</span>
    </footer>

    <br/><br/>

app/views/journals/show.html.erb
<%= javascript_pack_tag 'alert' %>

<%= render 'navbar' %>

    <div class="flex justify-center mt-8 gap-2 text-center font-semibold text-3xl">
        <%= @journal.name %>
    </div>

    <br/>

    <div class="flex justify-center gap-2 text-center text-xl">

        <div>
            <%= @journal.percent_complete %>% Task Completed
        </div>

        <div>
            <progress 
                class="progress is-normal is-success"
                value="<%= @journal.percent_complete %>" max="100">
            </progress>   
        </div>
        
        <%= link_to new_journal_task_path(@journal) do%>
            <i class="fas fa-plus mr-3" aria-hidden="true"></i>Task
        <% end %>     

    </div>

    <br/>

    <hr class="hr-task w-3/4 h-1 bg-gray-900"/>

    <br/>

    <%# If there is no task/s %>

    <% if @journal.tasks.count == 0 %>
        <div class="flex flex-col">
            <%= image_tag("empty-animate.svg", :alt => 'empty task image', class: "empty__svg") %>
            <div class="mt-8 flex gap-20 justify-center items-center">
                <p class="text-3xl font-semibold">No Tasks Yet</p>
                <%# Link ng New Task Path %>
                <%= link_to new_journal_task_path(@journal), class: 'text-3xl font-semibold' do%>
                    <i class="fas fa-plus mr-3" aria-hidden="true"></i>Add Task Now
                <% end %>
            </div>
        </div>
    <% else %>

    <%# Your Task/s %>
    
    <h1 class="text-center text-3xl font-bold text-gray-900">Your Task/s</h1>

    <div class="journal-index grid grid-cols-4 gap-8 max-w-7xl mt-16 custom:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-4">
            <% @journal.tasks.each do |task| %>

                    <% if task.completed? == false and !task.deadline.today? %>

                    <div class="journal__index bg-gray-50 border-2 border-gray-500 rounded-sm w-full p-8 custom:w-3/4 md:w-3/4 lg:w-3/4 xl:w-full 2xl:w-full">
                        <div class="tile tile-item is-parent is-shady tile-color">
                        <article class="tile is-child box card-bg"  id="task_box">
                        <%= raw task_label(task)[:html] %>
                        
                        <br>
                        <div class="tile-contents">
                            <strong class="text-3xl whitespace-nowrap"><%= task.name %></strong>  
                            <br/>
                            <span class="tasks-time">
                                <i class='bx bxs-time' ></i>         
                                <%= date_parse(task.deadline) %>
                            </span>
                            <br/>
                            <i class='bx bxs-chevron-right' ></i>
                            <span class='tasks-desc'>
                                <%= truncate(strip_tags(task.description.to_s), length: 100) %>
                            </span>
                        </div>

                            <br/>

                            <div class="tile-actions tasks-icons is-flex is-justify-content-flex-end">
                            
                                <%= link_to journal_task_path(@journal, task), class:"button  has-text-primary action-tile-button mr-2" do%>
                                    <i class='bx bx-expand-alt font-semibold text-violet-800 text-3xl hover:text-violet-600' ></i>
                                <% end %>
                                <%= link_to edit_journal_task_path(@journal, task), class:"button  has-text-warning action-tile-button mr-2" do%>
                                    <i class='bx bxs-edit-alt font-semibold text-yellow-800 text-3xl hover:text-yellow-600'></i>
                                <% end %>
                                <%= link_to journal_task_path(@journal, task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' }, class:"button has-text-danger" do %>
                                    <i class='bx bxs-trash font-semibold text-red-800 text-3xl hover:text-red-600' ></i>
                                <% end %>
                            </div>
                                
                        </article>
                        </div>
                    </div>

                    <% end %>

            <% end %>
    </div>

    <br/><br/>

    <%# Completed Task/s %>

    <% unless @journal.percent_complete == 0 %>
    
    <h1 class="text-center text-3xl font-bold text-green-900">Completed Task/s</h1>

    <div class="journal-index grid grid-cols-4 gap-8 max-w-7xl mt-16 custom:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-4">
            <% @journal.tasks.each do |task| %>

                <% unless task.completed? == false %>

                <div class="journal__index bg-gray-50 border-2 border-green-500 rounded-sm w-full p-8 custom:w-3/4 md:w-3/4 lg:w-3/4 xl:w-full 2xl:w-full">
                
                    <div class="tile tile-item is-parent is-shady tile-color">
                    <article class="tile is-child box card-bg"  id="task_box">
                    <div class="tile-contents">
                        <strong><%= task.name %></strong>  
                        <br/>
                        <span class="tasks-time">
                            <i class='bx bxs-time' ></i>         
                            <%= date_parse(task.deadline) %>
                        </span>
                        <br/>
                        <i class='bx bxs-chevron-right' ></i>
                        <span class='tasks-desc'>
                            <%= truncate(strip_tags(task.description.to_s), length: 100) %>
                        </span>
                    </div>

                        <br/>

                        <div class="tile-actions tasks-icons is-flex is-justify-content-flex-end">
                        
                            <%= link_to journal_task_path(@journal, task), class:"button  has-text-primary action-tile-button mr-2" do%>
                                <i class='bx bx-expand-alt font-semibold text-violet-800 text-3xl hover:text-violet-600' ></i>
                            <% end %>
                            <%= link_to edit_journal_task_path(@journal, task), class:"button  has-text-warning action-tile-button mr-2" do%>
                                <i class='bx bxs-edit-alt font-semibold text-yellow-800 text-3xl hover:text-yellow-600'></i>
                            <% end %>
                            <%= link_to journal_task_path(@journal, task), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' }, class:"button has-text-danger" do %>
                                <i class='bx bxs-trash font-semibold text-red-800 text-3xl hover:text-red-600' ></i>
                            <% end %>
                        </div>
                        
                    </article>
                    </div>
                </div>
                <% end %>
                
            <% end %>
    </div>

    <%# Do not delete this end %>

    <% end %>

<% end %>

<br/><br/>